### ISSUE TITLE
errors with python 3.8

### ISSUE THREAD

**Issue by retzkek** [fermitools/htgettoken#19]
Running htgettoken fails under python3.8, with the following error (and a warning):

```
python3 ./htgettoken -i $VO -a $VAULT_SERVER                                                                     
./htgettoken:961: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if auth_url is "":
Attempting to get token from [VAULT_SERVER] ...Traceback (most recent call last):
  File "./htgettoken", line 1146, in <module>
    main()
  File "./htgettoken", line 841, in main
    bearertoken = getBearerToken(opener, vaultserver,
  File "./htgettoken", line 430, in getBearerToken
    body = handle.read()
  File "/usr/local/lib/python3.8/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/usr/local/lib/python3.8/http/client.py", line 615, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(1025 bytes read, 307 more expected)
```

I've replicated this error on SL7 with Python 3.8.12 (compiled from source), and on MacOS Big Sur 11.5.2 arm64 with Python 3.8.11 (installed from nixpkgs).

**Comment by retzkek** [comment]
I started diving into the rabbit hole and hit a brick wall called M2Crypto and [its wonderful documentation](https://m2crypto.readthedocs.io/en/latest/M2Crypto.SSL.html). So I backed up and tried changing to the standard `HTTPSConnection`, which worked wonderfully. Note that as of Python 3.7 [cert hostnames are checked](https://docs.python.org/3/library/ssl.html#verifying-certificates) so I don't think there's any reason to not use the standard library.

@DrDaveD what do you think, put in a version check to decide which HTTPSConnection to use? 

For testing I just patched `VerifiedHTTPSHandler`, but probably needs a bit more thought:
```
diff --git a/htgettoken b/htgettoken
index febb9f1..b232836 100755
--- a/htgettoken
+++ b/htgettoken
@@ -272,7 +272,7 @@ class VerifiedHTTPSHandler(urllib_request.HTTPSHandler):
             full_kwargs = dict(self._connection_args)
             full_kwargs.update(kwargs)
             p = urllib_parse.urlsplit('https://'+netloc)
-            return CertValidatingHTTPSConnection(p.hostname, p.port, **full_kwargs)
+            return http_client.HTTPSConnection(p.hostname, p.port, **full_kwargs)
 
         return self.do_open(http_class_wrapper, req)
 
@@ -627,8 +627,8 @@ def main():
 
     parseargs(parser, envargs + sys.argv[1:])
 
-    httpshandler = VerifiedHTTPSHandler(
-        cafile=options.cafile, capath=options.capath)
+    context = ssl.SSLContext(cafile=options.cafile, capath=options.capath)
+    httpshandler = VerifiedHTTPSHandler(context=context)
     if options.debug:
         httpshandler.set_http_debuglevel(1)
     opener = urllib_request.build_opener(httpshandler)
```

**Comment by DrDaveD** [comment]
I have been able to reproduce the problem using the rh-python38-python package on el7, and found another workaround for the problem.  Please see if it fixes the problem for you.
