### ISSUE TITLE
Catch un-writeable areas

### ISSUE THREAD

**Issue by rlcee** [fermitools/htgettoken#22]
On a Fermilab-managed interactive server, when attempting to get a token 
while user's kerberos is expired, the process fails because the user home area is not 
writable without a kerberos ticket.  Suggest catching the error and exiting gracefully.

mu2egpvm01 ~ > htgettoken -i mu2e --vaultserver fermicloud543.fnal.gov
/bin/bash: /nashome/r/rlc/.bashrc: Key has expired
Attempting OIDC authentication with https://fermicloud543.fnal.gov:8200

Complete the authentication via web browser at:
    https://cilogon.org/device/?user_code=NVJ-VXV-DD6
No web open command defined, please open URL manually
Waiting for response in web browser
Storing vault token in /tmp/vt_u1311
Saving credkey to /nashome/r/rlc/.config/htgettoken/credkey-mu2e-default
Traceback (most recent call last):
  File "htgettoken", line 1079, in main
  File "os.py", line 210, in makedirs
  File "os.py", line 210, in makedirs
  File "os.py", line 210, in makedirs
  File "os.py", line 220, in makedirs
OSError: [Errno 127] Key has expired: '/nashome/r'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "htgettoken", line 1135, in <module>
  File "htgettoken", line 1081, in main
NameError: name 'configdir' is not defined
[8522] Failed to execute script 'htgettoken' due to unhandled exception!

**Comment by DrDaveD** [comment]
Thanks for the report.  It had attempted to catch the error but there was a bug in the error handling code.
